# Generated by Django 3.2.7 on 2021-11-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba', '0002_auto_20211104_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='cpd',
        ),
    ]
